# Generated by Django 5.0 on 2025-12-15 09:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("row_order", models.IntegerField(default=0)),
                ("collapsed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["row_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("manufacturer", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("default_polling_interval", models.IntegerField(default=5)),
                (
                    "register_definitions",
                    models.JSONField(
                        default=list,
                        help_text="JSON array with register configurations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["manufacturer", "model"],
            },
        ),
        migrations.CreateModel(
            name="ModbusInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("RTU", "Modbus RTU (Serial)"),
                            ("TCP", "Modbus TCP/IP"),
                        ],
                        max_length=3,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        default="offline",
                        max_length=10,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "port",
                    models.CharField(
                        blank=True,
                        help_text="Serial port (e.g., COM3, /dev/ttyUSB0)",
                        max_length=50,
                    ),
                ),
                (
                    "baudrate",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (9600, "9600"),
                            (19200, "19200"),
                            (38400, "38400"),
                            (57600, "57600"),
                            (115200, "115200"),
                        ],
                        default=9600,
                        null=True,
                    ),
                ),
                (
                    "parity",
                    models.CharField(
                        blank=True,
                        choices=[("N", "None"), ("E", "Even"), ("O", "Odd")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "stopbits",
                    models.IntegerField(blank=True, choices=[(1, "1"), (2, "2")], default=1, null=True),
                ),
                (
                    "bytesize",
                    models.IntegerField(blank=True, choices=[(7, "7"), (8, "8")], default=8, null=True),
                ),
                (
                    "host",
                    models.CharField(blank=True, help_text="IP address or hostname", max_length=100),
                ),
                (
                    "tcp_port",
                    models.IntegerField(
                        blank=True,
                        default=502,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "timeout",
                    models.FloatField(
                        default=3.0,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modbus Interface",
                "verbose_name_plural": "Modbus Interfaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.IntegerField()),
                (
                    "changes",
                    models.JSONField(default=dict, help_text="Dictionary of changes"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["timestamp"], name="modbus_app__timesta_68ed5f_idx"),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="modbus_app__model_n_0509fe_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slave_id",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(247),
                        ]
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "polling_interval",
                    models.IntegerField(
                        default=5,
                        help_text="Polling interval in seconds",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        default="offline",
                        max_length=10,
                    ),
                ),
                ("last_poll", models.DateTimeField(blank=True, null=True)),
                ("error_count", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="modbus_app.modbusinterface",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "function_code",
                    models.IntegerField(
                        choices=[
                            (1, "FC01 - Read Coils"),
                            (2, "FC02 - Read Discrete Inputs"),
                            (3, "FC03 - Read Holding Registers"),
                            (4, "FC04 - Read Input Registers"),
                            (5, "FC05 - Write Single Coil"),
                            (6, "FC06 - Write Single Register"),
                            (15, "FC15 - Write Multiple Coils"),
                            (16, "FC16 - Write Multiple Registers"),
                        ]
                    ),
                ),
                (
                    "address",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(65535),
                        ]
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("INT16", "16-bit Signed Integer"),
                            ("UINT16", "16-bit Unsigned Integer"),
                            ("INT32", "32-bit Signed Integer"),
                            ("UINT32", "32-bit Unsigned Integer"),
                            ("FLOAT32", "32-bit Float"),
                            ("BOOL", "Boolean"),
                        ],
                        default="UINT16",
                        max_length=10,
                    ),
                ),
                (
                    "byte_order",
                    models.CharField(
                        choices=[("big", "Big Endian"), ("little", "Little Endian")],
                        default="big",
                        max_length=10,
                    ),
                ),
                (
                    "word_order",
                    models.CharField(
                        choices=[
                            ("high_low", "High Word First"),
                            ("low_high", "Low Word First"),
                        ],
                        default="high_low",
                        max_length=10,
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        help_text="Multiply raw value by this factor",
                        max_digits=10,
                    ),
                ),
                (
                    "conversion_offset",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        help_text="Add this offset after multiplication",
                        max_digits=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (°C, kW, A, V, Hz, %, etc.)",
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("writable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registers",
                        to="modbus_app.device",
                    ),
                ),
            ],
            options={
                "ordering": ["device", "address"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("line_chart", "Line Chart"),
                            ("bar_chart", "Bar Chart"),
                            ("gauge", "Gauge"),
                            ("text", "Text Display"),
                            ("status", "Status Indicator"),
                        ],
                        default="line_chart",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "column_position",
                    models.IntegerField(
                        default=0,
                        help_text="Column position (0-11 for Bootstrap grid)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                ("row_position", models.IntegerField(default=0)),
                (
                    "width",
                    models.IntegerField(
                        default=6,
                        help_text="Width in Bootstrap columns (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "height",
                    models.IntegerField(default=300, help_text="Height in pixels"),
                ),
                ("trend_enabled", models.BooleanField(default=True)),
                (
                    "sample_rate",
                    models.IntegerField(
                        default=5,
                        help_text="Sample interval in seconds",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "aggregation_method",
                    models.CharField(
                        choices=[
                            ("none", "None (Raw Data)"),
                            ("mean", "Mean/Average"),
                            ("max", "Maximum"),
                            ("min", "Minimum"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "time_range",
                    models.IntegerField(
                        default=60,
                        help_text="Time window in minutes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "chart_color",
                    models.CharField(default="#007bff", help_text="Hex color code", max_length=7),
                ),
                ("show_legend", models.BooleanField(default=True)),
                (
                    "y_axis_mode",
                    models.CharField(
                        choices=[("auto", "Auto Scale"), ("static", "Static Range")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("y_axis_min", models.FloatField(blank=True, null=True)),
                ("y_axis_max", models.FloatField(blank=True, null=True)),
                (
                    "decimal_places",
                    models.IntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("show_unit", models.BooleanField(default=True)),
                (
                    "font_size",
                    models.IntegerField(
                        default=24,
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(72),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="modbus_app.dashboardgroup",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="modbus_app.register",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "row_position", "column_position"],
            },
        ),
        migrations.CreateModel(
            name="CalculatedRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "formula",
                    models.TextField(help_text="Python expression (e.g., 'register_1 + register_2 * 1.5')"),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "update_interval",
                    models.IntegerField(default=5, help_text="Recalculate every X seconds"),
                ),
                ("last_value", models.FloatField(blank=True, null=True)),
                ("last_calculated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculated_registers",
                        to="modbus_app.device",
                    ),
                ),
                (
                    "source_registers",
                    models.ManyToManyField(related_name="calculated_by", to="modbus_app.register"),
                ),
            ],
            options={
                "ordering": ["device", "name"],
            },
        ),
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("greater_than", "Greater Than"),
                            ("less_than", "Less Than"),
                            ("equals", "Equals"),
                            ("not_equals", "Not Equals"),
                            ("range", "Out of Range"),
                        ],
                        max_length=20,
                    ),
                ),
                ("threshold_high", models.FloatField()),
                ("threshold_low", models.FloatField(blank=True, null=True)),
                (
                    "hysteresis",
                    models.FloatField(default=0.0, help_text="Hysteresis to prevent alarm flapping"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("acknowledged", models.BooleanField(default=False)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(help_text="Alarm message/description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarms",
                        to="modbus_app.register",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "register"],
            },
        ),
        migrations.CreateModel(
            name="TrendData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("raw_value", models.FloatField()),
                ("converted_value", models.FloatField()),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("bad", "Bad"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="good",
                        max_length=10,
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend_data",
                        to="modbus_app.register",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trend Data",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TrendDataAggregated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("min_value", models.FloatField()),
                ("max_value", models.FloatField()),
                ("avg_value", models.FloatField()),
                ("sample_count", models.IntegerField()),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregated_data",
                        to="modbus_app.register",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trend Data Aggregated",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AlarmHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("triggered", "Triggered"),
                            ("cleared", "Cleared"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.FloatField()),
                ("message", models.TextField()),
                (
                    "alarm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="modbus_app.alarm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Alarm History",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["alarm", "-timestamp"],
                        name="modbus_app__alarm_i_cba2ff_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["interface", "enabled"], name="modbus_app__interfa_5661d6_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["connection_status"], name="modbus_app__connect_d0f2b9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("interface", "slave_id")},
        ),
        migrations.AddIndex(
            model_name="register",
            index=models.Index(fields=["device", "enabled"], name="modbus_app__device__2f414a_idx"),
        ),
        migrations.AddIndex(
            model_name="register",
            index=models.Index(fields=["function_code"], name="modbus_app__functio_a43e3f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="register",
            unique_together={("device", "address", "function_code")},
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(fields=["group", "row_position"], name="modbus_app__group_i_0b2b15_idx"),
        ),
        migrations.AddIndex(
            model_name="alarm",
            index=models.Index(fields=["register", "enabled"], name="modbus_app__registe_596a4e_idx"),
        ),
        migrations.AddIndex(
            model_name="alarm",
            index=models.Index(fields=["active", "acknowledged"], name="modbus_app__active_a555cc_idx"),
        ),
        migrations.AddIndex(
            model_name="trenddata",
            index=models.Index(fields=["register", "-timestamp"], name="modbus_app__registe_e2e208_idx"),
        ),
        migrations.AddIndex(
            model_name="trenddata",
            index=models.Index(fields=["timestamp"], name="modbus_app__timesta_58ebca_idx"),
        ),
        migrations.AddIndex(
            model_name="trenddata",
            index=models.Index(
                fields=["register", "quality", "-timestamp"],
                name="modbus_app__registe_c9cf72_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trenddataaggregated",
            index=models.Index(
                fields=["register", "interval", "-timestamp"],
                name="modbus_app__registe_602376_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trenddataaggregated",
            unique_together={("register", "interval", "timestamp")},
        ),
    ]
