# Generated by Django 5.0 on 2025-12-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modbus_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alarmhistory",
            options={
                "ordering": ["-triggered_at"],
                "verbose_name_plural": "Alarm History",
            },
        ),
        migrations.RemoveIndex(
            model_name="alarm",
            name="modbus_app__active_a555cc_idx",
        ),
        migrations.RemoveIndex(
            model_name="alarmhistory",
            name="modbus_app__alarm_i_cba2ff_idx",
        ),
        migrations.RenameField(
            model_name="alarm",
            old_name="triggered_at",
            new_name="last_triggered",
        ),
        migrations.RenameField(
            model_name="alarmhistory",
            old_name="value",
            new_name="trigger_value",
        ),
        migrations.RenameField(
            model_name="alarmhistory",
            old_name="timestamp",
            new_name="triggered_at",
        ),
        migrations.RemoveField(
            model_name="alarm",
            name="acknowledged",
        ),
        migrations.RemoveField(
            model_name="alarm",
            name="active",
        ),
        migrations.RemoveField(
            model_name="alarmhistory",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="alarmhistory",
            name="message",
        ),
        migrations.AddField(
            model_name="alarmhistory",
            name="acknowledged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alarmhistory",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alarmhistory",
            name="acknowledged_by",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="alarmhistory",
            name="cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="alarm",
            index=models.Index(
                fields=["last_triggered"], name="modbus_app__last_tr_80a180_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alarmhistory",
            index=models.Index(
                fields=["alarm", "-triggered_at"], name="modbus_app__alarm_i_7bb3cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alarmhistory",
            index=models.Index(
                fields=["cleared_at"], name="modbus_app__cleared_72f296_idx"
            ),
        ),
    ]
